// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace UklonBot.Models.Recieve
{

    public class Sender
    {
        public string id;
        public string name;
        public string avatar;
    }

    public class Location
    {
        public double lat;
        public double lon;
    }

    public class Message
    {
        public string type;
        public string text;
        public string media;
        public Location location;
        public string tracking_data;
    }

    public class User
    {
        public string id;
        public string name;
        public string avatar;
        public string country;
        public string language;
        public int api_version;
    }

    public class ViberCallbackModel
    {
        public ViberCallbackModel()
        { }

        [JsonProperty(PropertyName = "event")]
        public string callback_event { get; set; }

        [JsonProperty(PropertyName = "timestamp")]
        public long? timestamp { get; set; }

        [JsonProperty(PropertyName = "message_token")]
        public long? message_token { get; set; }

        public string user_id;
        public string desc;
        public string type;
        public string context;
        public User user;
        public Sender sender;
        public Message message;
    }

}